---
title: "State-space models"
author: "Robin Aldridge-Sutton"
date: "04/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# White noise

$$e_t \sim N(0, \sigma^2)$$

```{r}
n_t <- 20
n_samps <- 5
sigma <- 1
e <- matrix(rnorm(n_t * n_samps, sd = sigma), nrow = n_t)
matplot(e, type = 'l', xlab = "Time", ylab = "Value",
        main = "White noise", col = 1, lty = 1)
lines(rep(0, n_t), col = 'red')
lines(rep(1.96, n_t), col = 'red', lty = 2)
lines(rep(-1.96, n_t), col = 'red', lty = 2)
```

# Random walk (Brownian motion)

$$a_t \sim N(0, \tau^2)$$
$$\mu_{t + 1} = \mu_t + a_t$$
$$\mu_t \sim N(0, t \tau^2)$$

```{r}
tau <- 1
a <- matrix(rnorm(n_t * n_samps, sd = tau), nrow = n_t)
mu <- apply(a, 2, cumsum)
matplot(mu, type = 'l', xlab = "Time", ylab = "Value",
        main = "Random walk", col = 1, lty = 1)
lines(rep(0, n_t), col = 'red')
t <- 1:n_t
lines(1.96 * sqrt(t), col = 'red', lty = 2)
lines(-1.96 * sqrt(t), col = 'red', lty = 2)
```

# Random walk plus white noise

$$y_t = \mu_t + e_t$$
$$y_t \sim N(0, t \tau^2 + \sigma^2)$$

```{r}
y <- mu + e
matplot(y, type = 'l', xlab = "Time", ylab = "Value",
        main = "Random walk plus white noise", col = 1, lty = 1)
lines(rep(0, n_t), col = 'red')
lines(1.96 * sqrt(t + 1), col = 'red', lty = 2)
lines(-1.96 * sqrt(t + 1), col = 'red', lty = 2)
```

# Quarterly random walks

$$\mu_{t + 1} = \mu_{t - 3} + a_t$$
$$\mu_t \sim N \left( 0, ceiling \left( \frac{t}{4} \right) \tau^2 \right)$$

```{r}
mu_q <- apply(a, 2, function(column) 
  as.vector(t(apply(matrix(column, ncol = 4, byrow = T), 2, cumsum))))
matplot(mu_q, type = 'l', xlab = "Time", ylab = "Value",
        main = "Quarterly random walks", col = 1, lty = 1)
grid(nx = n_t / 4, ny = NA)
lines(rep(0, n_t), col = 'red')
lines(1.96 * sqrt(ceiling(t / 4)), col = 'red', lty = 2)
lines(-1.96 * sqrt(ceiling(t / 4)), col = 'red', lty = 2)
```

# Quarterly random walks plus noise

$$y_t = \mu_t + e_t$$

$$\mu_t \sim N \left( 0, ceiling \left( \frac{t}{4} \right) \tau^2 + \sigma \right)$$

```{r}
y_q <- mu_q + e
matplot(y_q, type = 'l', xlab = "Time", ylab = "Value",
        main = "Quarterly random walks plus white noise", col = 1, lty = 1)
grid(nx = n_t / 4, ny = NA)
lines(rep(0, n_t), col = 'red')
lines(1.96 * sqrt(ceiling(t / 4) + 1), col = 'red', lty = 2)
lines(-1.96 * sqrt(ceiling(t / 4) + 1), col = 'red', lty = 2)
```

# Evolving variance

$$h_{t + 1} = h_t + a_t$$
$$y_t = \exp \left( \frac{h_t}{2} \right) e_t$$
$$y_t \not\sim N$$
$$E(y_t) = 0$$
$$var(y_t) = \exp(h_t)$$
$$\log\{var(y_t)\} \sim N(0, t \tau^2)$$

```{r}
h <- mu
y_v <- exp(h / 2) * e
matplot(y_v, type = 'l', xlab = "Time", ylab = "Value",
        main = "Evolving variance", col = 1, lty = 1)
lines(rep(0, n_t), col = 'red')
```

